# Dependencies
markdown:         kramdown
highlighter:      pygments

# Gems
gems: [jekyll-paginate]
gems: [citeproc]
gems: [csl/styles]
gems: [jekyll/scholar]

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:      Alfredo Garbuno
name:			  Alfredo Garbuno
description:      'Postdoctoral Scholar at <a href="http://www.caltech.edu/" target="_blank">Caltech</a>.'
url:              
baseurl:          /

author:
  name:     'Alfredo Garbuno'

#plugins: 
#  - jekyll-paginate
#paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/agarbuno

twitter_username:     AlfredoGarbuno
github_username:      agarbuno
linkedin_username:    agarbuno
google_plus_username: AlfredoGarbunoIñigo

scholar:
  style: apa
  repository: public/pdf
  replace_strings: true
  join_strings: true
  bibliography_template: bibliography
  sort_by: year
  order: descending