# Dependencies
markdown:         kramdown
highlighter:      pygments

# Gems
gems: [jekyll-paginate]
gems: [citeproc]
gems: [csl/styles]
gems: [jekyll/scholar]

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:        Alfredo Garbuno I単igo
name:		  Alfredo Garbuno I単igo
description: 'Assistant Professor at <a href="http://www.itam.mx/" target="_blank">ITAM</a>.'
url:
baseurl:     /

author:
  name:     'Alfredo Garbuno I単igo'

#plugins:
#  - jekyll-paginate
#paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/agarbuno

twitter_username:     AlfredoGarbuno
github_username:      agarbuno
linkedin_username:    agarbuno
google_plus_username: AlfredoGarbunoI単igo

scholar:
  style: apa
  repository: public/pdf
  replace_strings: true
  join_strings: true
  bibliography_template: bibliography
  sort_by: year
  order: descending
